### ISSUE TITLE
Wordpress There has been a critical error on this website.

### ISSUE THREAD

**Issue by jaycova** [bitnami/vms#1061]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

1f98a780-04a1-34ea-0292-bb63acbcaa9e

### bndiagnostic output

✓ Resources: No issues found
    ✓ Connectivity: No issues found
    ✓ Mariadb: No issues found
    ✓ Processes: No issues found
    ? Wordpress: Found possible issues
    ✓ Apache: No issues found
    ✓ Php: No issues found
 

 
[Wordpress]

Found recent WordPress plugin related error messages in the Apache error log.
```
[Tue Jul 25 13:36:23.250010 2023] [proxy_fcgi:error] [pid 1189:tid 
140549650446080] [client **ip_address**:58078] AH01071: Got error 'PHP message: 
PHP Fatal error: Uncaught Error: Class 
"ComposerAutoloaderInitf66b514c0dd319aa69bf24c9d19b0fbd" not found in 
/bitnami/wordpress/wp-content/plugins/leadin/vendor/autoload.php:25
Press [Enter] to continue:
Stack trace:
#0 /bitnami/wordpress/wp-content/plugins/leadin/leadin.php(73): require_once()
#1 /opt/bitnami/wordpress/wp-settings.php(453): include_once('...')
#2 /bitnami/w
```
Please check the following guide to deactivate plugins:

### bndiagnostic was not useful. Could you please tell us why?

I tried to deactivate all plugins but it did not help

### Describe your issue as much as you can

Website is just down. I had Wordpress try and repair some plugins and now it is down.

**Comment by jaycova** [comment]
I fixed this. I copied the /bitnami/wordpress/wp-content/plugins/leadin/ directory over from another server and it came up. Sorry I didn't think of this sooner.
