### ISSUE TITLE
[alfresco] Problem with SOLR

### ISSUE THREAD

**Issue by fbacapro** [bitnami/vms#108]
### Platform

Virtual Machine

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

n

### bndiagnostic was not useful. Could you please tell us why?

it didnt work

### Describe your issue as much as you can

Hi,
I Installed Alfresco 7.0 (from bitnami OVA) few weeks ago.
Then I updated my system with apt few days ago.
Since then, solr wont start.

Here is the log 
`
2022-07-12 09:37:05.622 INFO  (main) [   ] o.e.j.s.Server jetty-9.3.29.v20201019, build timestamp: 2020-10-19T18:29:13Z, git hash: dc45408dd3f9543c51643ececa5dca76ca08d219
2022-07-12 09:37:06.406 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr ^d  version 6.6.5-patched.6 b7de23b72dd7fa3aceb22202f4b27683546a7139 - aborroy - 2021-06-17 16:20:23
2022-07-12 09:37:06.407 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in standalone mode on port 8983
2022-07-12 09:37:06.407 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: /opt/bitnami/alfresco-search-services/solr
2022-07-12 09:37:06.416 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2022-07-12T09:37:06.408446Z
2022-07-12 09:37:10.099 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.c.Config XML parse warning in "solrres:/solrconfig.xml", line 1959, column 88: Include operation failed, reverting to fallback. R$
2022-07-12 09:37:10.101 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.c.Config XML parse warning in "solrres:/solrconfig.xml", line 1959, column 88: Include operation failed, reverting to fallback. Re$
2022-07-12 09:37:10.166 INFO  (main) [   ] o.e.j.s.Server Started @6730ms
2022-07-12 09:37:10.394 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.c.Config You should not use LATEST as luceneMatchVersion property: if you use this setting, and then Solr upgrades to a newer rel$
2022-07-12 09:37:10.569 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.c.Config Beginning with Solr 5.5, <mergePolicy> is deprecated, use <mergePolicyFactory> instead.
2022-07-12 09:37:10.592 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.c.Config Beginning with Solr 5.5, <mergePolicy> is deprecated, use <mergePolicyFactory> instead.
2022-07-12 09:37:12.102 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [org.apache.solr.analysis.WordDelimiterFilterFactory]. Please$
2022-07-12 09:37:12.119 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.c.SolrResourceLoader Solr loaded a deprecated plugin/analysis class [solr.SynonymFilterFactory]. Please consult documentation how$
2022-07-12 09:37:12.642 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field content@s____@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.642 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field content@s__lt@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.642 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field text@s__sort@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.642 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field text@s____@* is not multivalued and destination for multiple copyFields (16)
2022-07-12 09:37:12.643 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field content@s__l_@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.643 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field text@s__l_@* is not multivalued and destination for multiple copyFields (16)
2022-07-12 09:37:12.643 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field text@s__lt@* is not multivalued and destination for multiple copyFields (16)
2022-07-12 09:37:12.643 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field text@s___t@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.643 WARN  (coreLoadExecutor-6-thread-1) [   x:alfresco] o.a.s.s.IndexSchema Field content@s___t@* is not multivalued and destination for multiple copyFields (4)
2022-07-12 09:37:12.646 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field content@s____@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.653 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field content@s__lt@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.653 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field text@s__sort@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.653 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field text@s____@* is not multivalued and destination for multiple copyFields (16)
2022-07-12 09:37:12.653 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field content@s__l_@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.653 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field text@s__l_@* is not multivalued and destination for multiple copyFields (16)
2022-07-12 09:37:12.653 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field text@s__lt@* is not multivalued and destination for multiple copyFields (16)
2022-07-12 09:37:12.653 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field text@s___t@* is not multivalued and destination for multiple copyFields (8)
2022-07-12 09:37:12.653 WARN  (coreLoadExecutor-6-thread-2) [   x:archive] o.a.s.s.IndexSchema Field content@s___t@* is not multivalued and destination for multiple copyFields (4)
2022-07-12 09:37:15.506 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be created
java.util.concurrent.ExecutionException: org.apache.solr.common.SolrException: Unable to create core [alfresco]
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.apache.solr.core.CoreContainer.lambda$load$6(CoreContainer.java:594)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.solr.common.SolrException: Unable to create core [alfresco]
        at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:966)
        at org.apache.solr.core.CoreContainer.lambda$load$5(CoreContainer.java:565)
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
        ... 5 more
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:977)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:830)
        at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:950)
        ... 7 more
Caused by: org.apache.solr.common.SolrException: Error opening new searcher
        at org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:2069)
        at org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:2189)
        at org.apache.solr.core.SolrCore.initSearcher(SolrCore.java:1071)
        at org.apache.solr.core.SolrCore.<init>(SolrCore.java:949)
        ... 9 more
`

Can you help please ?

Regards

**Comment by mdhont** [comment]
Can you check available RAM?

    free -m

Which issue do you have when running the bndiagnostic tool?

    sudo /opt/bitnami/bndiagnostic-tool

**Comment by fbacapro** [comment]
It hase plenty of RAM available 
`              total        used        free      shared  buff/cache   available
Mem:           7978        2958        4404           9         615        4779
`

Here is the bndiag (worked this time) :
`[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Apache]

Found recent error or warning messages in the Apache error log.
```
Press [Enter] to continue:
[Mon Jul 11 09:38:24.181910 2022] [proxy_ajp:error] [pid 693:tid
140301943203584] (70007)The timeout specified has expired: AH01030:
ajp_ilink_receive() can't receive header

[Mon Jul 11 09:38:24.181985 2022] [proxy_ajp:error] [pid 693:tid
140301943203584] [client **ip_address**:59814] AH00992: ajp_read_header:
ajp_ilink_receive failed

[Mon Jul 11 09:38:24.181996 2022] [proxy_ajp:error] [pid 693:tid
140301943203584] (70007)The timeout specified has expired: [client
**ip_address**:59814] AH00878: read response failed from [::1]:8009 (localhost)

```
Please check the following guide to troubleshoot server issues:

https://docs.bitnami.com/general/apps/wordpress/troubleshooting/debug-erro
rs-apache/


===== End of bndiagnostic tool output =====
`

**Comment by mdhont** [comment]
The bndiagnostic tool should show a 16 character long ID at the end, could you paste that here?

**Comment by fbacapro** [comment]
Hi, 

I'm back from short holiday,

I dig into my problem, and it seems that it is a credential problem.
I connected alfresco to windows AD with ldap, and it works, all users are able to log into alfresco.
But local alfresco users (like admin) cant log anymore. Only AD Users can.
I think I have a problem in my .properties file. Dont know where yet.

Regardes,

**Comment by jotamartos** [comment]
>I think I have a problem in my .properties file. Dont know where yet.

In that case, please review the app's documentation and its forum to get more information about the issue. 

Thanks!
