### ISSUE TITLE
[ERPNext] install hrms on erpnext 14 

### ISSUE THREAD

**Issue by anthonylkm0613** [bitnami/vms#1180]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

i have no ideas

### bndiagnostic output

ERROR: /home/bitnami is not a valid bench directory. Run with --init-bench if you'd like to create a Bench too.
Traceback (most recent call last):
  File "/opt/bitnami/erpnext/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/opt/bitnami/erpnext/bench/bench/cli.py", line 127, in cli
    bench_command()
  File "/opt/bitnami/erpnext/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bitnami/erpnext/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/bitnami/erpnext/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bitnami/erpnext/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bitnami/erpnext/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/bitnami/erpnext/bench/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/opt/bitnami/erpnext/bench/bench/app.py", line 385, in get_app
    raise NotInBenchDirectoryError(
bench.exceptions.NotInBenchDirectoryError: /home/bitnami is not a valid bench directory. Run with --init-bench if you'd like to create a Bench too.
INFO: A newer version of bench is available: 5.16.2 → 5.17.2

### bndiagnostic was not useful. Could you please tell us why?

i have no ideas

### Describe your issue as much as you can

After i use the AMI on aws to create the erpnext 14.21.0.0  (ami name : bitnami-erpnext-14.21.0-0-linux-debian-11-x86_64-hvm-ebs-nami), i try to login via ssh to install the hrms. 
i tried the command bench get-app hrms

it says : ERROR: /home/bitnami is not a valid bench directory. Run with --init-bench if you'd like to create a Bench too.

how can i correctly install the hrms ? thank you

**Comment by jotamartos** [comment]
>bench.exceptions.NotInBenchDirectoryError: /home/bitnami is not a valid bench directory. Run with --init-bench if you'd like to create a Bench too.

That's a specific error of the bench tool. You need to run it in the correct directory. Please change directories before running the bench command 

```
cd /opt/bitnami/frappe-bench
```

**Comment by anthonylkm0613** [comment]
thank you. i now at the correct rappe-bench directory and can run the get-app command. and it went well. however, when i need to execute below command, what should i put at to replace the mysite.localhost(i saw an example from youtube and they put "mysite.localhost" as the parrameter. how can i set this parameter correct? e.g. the url to acess my erpnext is  www. unitedexpress.com)

command:
bitnami@ip-172-31-38-221:~/stack/erpnext/frappe-bench$ bench --sites mysite.localhost install-app hrms

**Comment by anthonylkm0613** [comment]
and i would like the hr module is part of the erpnext menu. so could you let me know what the SITE Name i should create ?

**Comment by jotamartos** [comment]
> how can i set this parameter correct? e.g. the url to acess my erpnext is [www](http://www/). unitedexpress.com)
> 
> command:
> bitnami@ip-172-31-38-221:~/stack/erpnext/frappe-bench$ bench --sites mysite.localhost install-app hrms

You should use your domain name when running the command. 

>and i would like the hr module is part of the erpnext menu. so could you let me know what the SITE Name i should create ?

That's a app-specific question. Please take a look at the app's forums and documentation to know what you need to do to achieve what you want.

**Comment by anthonylkm0613** [comment]
i can go futher on  bench new-site command and below are what i executed and results with some error. when i run the command, it ask me the mysql root password.




bitnami@ip-172-31-43-101:/opt/bitnami/erpnext/frappe-bench$ bench new-site dragonwinmotors.online
MySQL root password: 
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/bitnami/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/commands/site.py", line 77, in new_site
    _new_site(
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/installer.py", line 80, in _new_site
    install_db(
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/installer.py", line 156, in install_db
    setup_database(force, source_sql, verbose, no_mariadb_socket)
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/database/__init__.py", line 20, in setup_database
    return frappe.database.mariadb.setup_db.setup_database(
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/database/mariadb/setup_db.py", line 36, in setup_database
    if force or (db_name not in dbman.get_database_list()):
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/database/db_manager.py", line 49, in get_database_list
    return self.db.sql("SHOW DATABASES", pluck=True)
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/database/database.py", line 200, in sql
    self.connect()
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/database/database.py", line 114, in connect
    self._conn = self.get_connection()
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "/opt/bitnami/erpnext/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/opt/bitnami/erpnext/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'127.0.0.1' (using password: YES)")

**Comment by jotamartos** [comment]
>pymysql.err.OperationalError: (1045, "Access denied for user '_8b1fa960deb3aed2'@'127.0.0.1' (using password: YES)")

That's not a user/password we configure. Did you modify something in the configuration? If you continue running into issues, please contact the plugin's developer.

**Comment by anthonylkm0613** [comment]
i didn't modify the configuration.  :<

**Comment by jotamartos** [comment]
Everything worked as expected for me. Please remember to move to the frappe-bench directory and activate the venv 

```
cd /opt/bitnami/erpnext/frappe-bench/
. ../venv/bin/activate
# Install nodejs and yarn
bench get-app hrms --branch v14.13.0
sudo su daemon -s /bin/bash -c "bench --site erpnext install-app hrms"
```

I installed it in the default site and the installation succeeded 

```
(venv) bitnami@ip-172-31-85-108:/opt/bitnami/erpnext/frappe-bench$ sudo su daemon -s /bin/bash -c "bench --site erpnext install-app hrms"
App erpnext already installed

Installing hrms...
Updating DocTypes for hrms          : [========================================] 100%
Setting up Frappe HR...

Patching Existing Data...
rename_field: kra_title not found in table for: Appraisal Template
rename_field: kra_template not found in table for: Appraisal
Thank you for installing Frappe HR!
Updating Dashboard for hrms
```

Please remember to use daemon if you get a permission-related error. If you continue running into issues when installing the app in your site, please check that the database credentials are correct and contact the plugin's developer if you continue running into issues.

**Comment by anthonylkm0613** [comment]
thank you i shall try this and get back you the result. thank you for your help

**Comment by anthonylkm0613** [comment]
thank you again jotamartos

i try your comments and it shows exactly results of your post and seems it is installed. however, when i try to login back the erpnext which i expect i can see all modules and the new HR module on the manual. it shows error page as attached

<img width="1331" alt="螢幕截圖 2023-10-12 上午10 07 42" src="https://github.com/bitnami/vms/assets/1542696/4cace85c-c468-422b-bc0d-670db15906ff">
 
also i show you the installation results as below : 
<img width="1001" alt="螢幕截圖 2023-10-12 上午10 08 26" src="https://github.com/bitnami/vms/assets/1542696/1beb71e9-66f1-4c7d-9513-d6067d5bb80e">

Or, should i install it on a new site rather than "erpnext" which maybe overwritten ? 

Thank you again for your advices.

**Comment by anthonylkm0613** [comment]
hi all, 
i just like to update the result. we try thoese recommended steps and it works well in another aws account. then we make the successful instance as private image and then i install it on my aws account which have errors shown when i tried those steps. 

Now it works well. thank you jotamartos and all.
