### ISSUE TITLE
Canvaslms Error when compile assets.

### ISSUE THREAD

**Issue by robertoromeroGA** [bitnami/vms#120]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

6f423f50-ee1b-42f3-70f2-140813006f90

### bndiagnostic output

    ✓ Apache: No issues found
    ✓ Connectivity: No issues found
    ? Resources: Found possible issues
    ✓ Processes: No issues found

### bndiagnostic was not useful. Could you please tell us why?

bndiagnostic has not provided information about the application error.

### Describe your issue as much as you can

This Canvaslms was launched with a Bitnami AMI on aws from Marketplace.

It was installed and configured correctly, today we have no problem in production but we need to compile the assets and I have this error.

The instance has 8gb of RAM and I have tried stopping processes in case the problem was the RAM and nothing. No matter the way, this problem always appears

When you perform the following command to compile the assets in production: `RAILS_ENV=production bundle exec rake canvas:compile_assets --trace`, you get the following error: 

```
rake aborted!
Parallel::DeadWorker: Parallel::DeadWorker
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:86:in 'rescue in work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:83:in 'work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:411:in 'block (4 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:527:in 'with_instrumentation'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:410:in 'block (3 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in 'loop'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in 'block (2 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:222:in 'block (4 levels) in in_threads'

Caused by:
EOFError: end of file reached
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/core_ext/marshal.rb:6:in 'load'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/core_ext/marshal.rb:6:in 'load'
/opt/bitnami/canvaslms/gems/canvas_ext/lib/canvas_ext/marshal.rb:27:in 'load'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:84:in 'work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:411:in 'block (4 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:527:in 'with_instrumentation'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:410:in 'block (3 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in 'loop'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in 'block (2 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:222:in 'block (4 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
```

**Comment by mdhont** [comment]
Are you running the command with sudo?

    sudo RAILS_ENV=production bundle exec rake canvas:compile_assets --trace

**Comment by robertoromeroGA** [comment]
Yes, and I got the same error:


```
--> Finished: 'js:yarn_install' in 29.7s
rake aborted!
Parallel::DeadWorker: Parallel::DeadWorker
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:86:in `rescue in work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:83:in `work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:411:in `block (4 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:527:in `with_instrumentation'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:410:in `block (3 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in `loop'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in `block (2 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:222:in `block (4 levels) in in_threads'

Caused by:
EOFError: end of file reached
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/core_ext/marshal.rb:6:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.2/lib/active_support/core_ext/marshal.rb:6:in `load'
/opt/bitnami/canvaslms/gems/canvas_ext/lib/canvas_ext/marshal.rb:27:in `load'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:84:in `work'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:411:in `block (4 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:527:in `with_instrumentation'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:410:in `block (3 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in `loop'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:398:in `block (2 levels) in work_in_processes'
/opt/bitnami/ruby/lib/ruby/gems/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:222:in `block (4 levels) in in_threads'
Tasks: TOP => canvas:compile_assets
```
