### ISSUE TITLE
[Solr] File Permission error when creating a core

### ISSUE THREAD

**Issue by s-paquette** [bitnami/vms#1234]
### Platform

Google Cloud Platform

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

2ae4cb81-8d71-c5cc-2971-a25a34694a68

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

    ✓ Apache: No issues found
    ✓ Processes: No issues found
    ✓ Resources: No issues found
    ? Connectivity: Found possible issues

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

Did not identify any issues which were relevant--this command is being run from the command line so the lack of available ports to public access is not applicable.

### Describe your issue as much as you can

After launching a Bitnami Solr image, I am unable to create a core. I've double-checked that my credentials are correct, and can successfully access to Solr homepage. If use the same basic setup from an older Bitnami image everything is fine. But when I run the create command from the current image via /opt/bitnami/solr/bin/solr I get the following:
```
user@solr-vm:~$ sudo -u solr solr create -c testcore

ERROR: Error from server at http://localhost:8983/solr/admin/cores?action=CREATE&name=testcore&instanceDir=testcore&wt=javabin&version=2: Error CREATEing SolrCore 'testcore': Unable to create core [testcore] Caused by: access denied ("java.io.FilePermission" "/bitnami/solr/server/solr/testcore/data/snapshot_metadata" "read")
```

If I attempt to make it again:
```
user@solr-vm:~$ sudo -u solr solr create -c testcore

ERROR:
Core 'testcore' already exists!
Checked core existence using Core API command
```

However, no core directories were made: 

```
user@solr-vm:~$ ls -l /opt/bitnami/solr/server/solr/
total 20
drwxrwxr-x 4 bitnami solr 4096 Nov 14 17:41 configsets
-rw-r--r-- 1 bitnami solr 3014 Nov 14 17:41 README.md
-rw-r--r-- 1 bitnami solr  627 Nov 14 19:53 security.json
-rw-r--r-- 1 bitnami solr 3549 Nov 14 17:41 solr.xml
-rw-r--r-- 1 bitnami solr 1048 Nov 14 17:41 zoo.cfg
```

A status request indicates the initialization failure:
```
user@solr-vm:~$ curl -u user:pass "http://localhost:8983/solr/admin/cores?action=STATUS&name=testcore"
{
  "responseHeader":{
    "status":0,
    "QTime":0
  },
  "initFailures":{
    "bob":"org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: access denied (\"java.io.FilePermission\" \"/bitnami/solr/server/solr/bob/data/snapshot_metadata\" \"read\")",
    "testcore":"org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: access denied (\"java.io.FilePermission\" \"/bitnami/solr/server/solr/testcore/data/snapshot_metadata\" \"read\")"
  },
  "status":{ }
```

This is just right out of the box, with no config changes beyond setting up a login and password (confirmed to work). If there's a permission issue, where is it and what needs to be set? (Or will you be releasing a new image where this is fixed?)

**Comment by jotamartos** [comment]
Thanks for reporting this issue. Let us reproduce it and will update this thread when having more information

**Comment by jotamartos** [comment]
I just worked on this and could create a new core by using these commands

```
export SOLR_AUTH_TYPE="basic"
export SOLR_AUTHENTICATION_OPTS="-Dbasicauth=USER:PASSWORD"
sudo -E su solr -c "solr create -c jota1"
```

![Screenshot 2023-11-20 at 13 25 30](https://github.com/bitnami/vms/assets/8791635/f6883242-16b7-4ebd-9463-fb3121370d02)

**Comment by s-paquette** [comment]
I am still seeing this error on the console when I use those exact commands (VM generated this morning):
```
user@solr-11-1-vm:~$ export SOLR_AUTH_TYPE="basic"
user@solr-11-1-vm:~$ export SOLR_AUTHENTICATION_OPTS="-Dbasicauth=user:pass"
user@solr-11-1-vm:~$ sudo -E su solr -c "solr create -c test"
WARNING: Using _default configset with data driven schema functionality. NOT RECOMMENDED for production use.
         To turn off: bin/solr config -c test -p 8983 -action set-user-property -property update.autoCreateFields -value false

ERROR: Error from server at http://localhost:8983/solr/admin/cores?action=CREATE&name=test&instanceDir=test&wt=javabin&version=2: Error CREATEing SolrCore 'test': Unable to create core [test] Caused by: access denied ("java.io.FilePermission" "/bitnami/solr/server/solr/test/data/snapshot_metadata" "read")
```

And I am unable to load any fields:

```
user@solr-11-1-vm:~$ curl -u user:pass -X POST -H 'Content-type:application/json' --data-binary '{"add-field": [{'name': 'field1', 'type': 'string', 'multiValued': False, 'stored': True}]}' http://localhost:8983/solr/test/schema
{
  "error":{
    "metadata":["error-class","org.apache.solr.core.SolrCoreInitializationException","root-error-class","java.security.AccessControlException"],
    "msg":"SolrCore 'test' is not available due to init failure: access denied (\"java.io.FilePermission\" \"/bitnami/solr/server/solr/test/data/snapshot_metadata\" \"read\")",
```

Is there possibly an issue when the VM is being made from the Bitnami or Google launch portals?

**Comment by jotamartos** [comment]
Hi @s-paquette,

Please ensure the machine has been booted correctly and that is has enough RAM memory to work. As I mentioned above, the commands worked for me when using the correct user. 

>Is there possibly an issue when the VM is being made from the Bitnami or Google launch portals?

These are the options you have to launch this solution in the cloud 

https://bitnami.com/stack/solr/cloud

**Comment by s-paquette** [comment]
@jotamartos Having gone through this a few more times, I've narrowed down the issue. The `security.json` file provided in the image doesn't grant core-creation abilities to the admin user, only `security-edit`:
```
cat /opt/bitnami/solr/server/solr/security.json
{
  "authentication":{
    "blockUnknown":true,
    "class":"solr.BasicAuthPlugin",
    "credentials":{"admin":"xxxx xxxxx"},
    "forwardCredentials":false,
    "":{"v":0}},
  "authorization":{
    "class":"solr.RuleBasedAuthorizationPlugin",
    "permissions":[{
        "name":"security-edit",
        "role":"admin"}],
    "user-role":{"admin":"admin"}}}
```
Theoretically I should need to add a new user which does have the right permissions (via the Auth API), and then core creation would work. But for some reason core creation works regardless when the VM is first booted, despite the admin account clearly not having sufficient permissions in `security.json`:
```
export SOLR_AUTH_TYPE="basic"
export SOLR_AUTHENTICATION_OPTS="-Dbasicauth=admin:xxxxxxx"
sudo -E su solr -c "solr create -c test_before_restart"
WARNING: Using _default configset with data driven schema functionality. NOT RECOMMENDED for production use.
         To turn off: bin/solr config -c test_before_restart -p 8983 -action set-user-property -property update.autoCreateFields -value false

Created new core 'test_before_restart'
```

If a Solr restart is performed, I get two warnings, one citing a lack of `bc` and one citing a lack of `lsof`:
```
sudo -E su solr -c "solr restart"
*** [WARN] *** Your open file limit is currently 1024.
 It should be set to 65000 to avoid operational disruption.
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
*** [WARN] ***  Your Max Processes Limit is currently 32768.
 It should be set to 65000 to avoid operational disruption.
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Sending stop command to Solr running on port 8983 ... waiting up to 180 seconds to allow Jetty process 2555 to stop gracefully.
Java 17 detected. Enabled workaround for SOLR-16463
/opt/bitnami/solr/bin/solr: line 2408: bc: command not found
NOTE: Please install lsof as this script needs it to determine if Solr is listening on port 8983.
```

And now, post restart, I can no longer create cores:
```
sudo -E su solr -c "solr create -c test_after_restart"
WARNING: Using _default configset with data driven schema functionality. NOT RECOMMENDED for production use.
         To turn off: bin/solr config -c test_after_restart -p 8983 -action set-user-property -property update.autoCreateFields -value false

ERROR: Error from server at http://localhost:8983/solr/admin/cores?action=CREATE&name=test_after_restart&instanceDir=test_after_restart&wt=javabin&version=2: Error CREATEing SolrCore 'test_after_restart': Unable to create core [test_after_restart] Caused by: access denied ("java.io.FilePermission" "/bitnami/solr/server/solr/test_after_restart/data/snapshot_metadata" "read")
```

This is with me making no changes to the VM, simply deploying it and performing the commands above. So something is clearly wrong in the configuration for security, but I can't see where it is, and it only becomes evident after restarting Solr.

**Comment by s-paquette** [comment]
@jotamartos Have you been able to confirm if there's an issue with the VM's user settings for the solr user? As I said, if I restart Solr in any capacity I can no longer make cores; the solr user doesn't appear to have the proper access.

**Comment by s-paquette** [comment]
After a bit more sleuthing, it looks like the restart script is likely the issue. In checking my logs, the first restart after a successful core creation yields this:

```
2024-01-02 20:09:03.421 INFO  (main) [] o.e.j.s.Server jetty-10.0.17; built: 2023-10-09T18:22:21.150Z; git: af15f12297adf5c5083e1f2f8f4c5974438bca25; jvm 17.0.9+11-LTS
2024-01-02 20:09:04.053 WARN  (main) [] o.e.j.u.DeprecationWarning Using @Deprecated Class org.eclipse.jetty.servlet.listener.ELContextCleaner
2024-01-02 20:09:04.114 INFO  (main) [] o.a.s.s.CoreContainerProvider Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
2024-01-02 20:09:04.126 INFO  (main) [] o.a.s.s.CoreContainerProvider  ___      _       Welcome to Apache Solr™ version 9.4.0
2024-01-02 20:09:04.126 INFO  (main) [] o.a.s.s.CoreContainerProvider / __| ___| |_ _   Starting in standalone mode on port 8983
2024-01-02 20:09:04.126 INFO  (main) [] o.a.s.s.CoreContainerProvider \__ \/ _ \ | '_|  Install dir: /opt/bitnami/solr
2024-01-02 20:09:04.126 INFO  (main) [] o.a.s.s.CoreContainerProvider |___/\___/_|_|    Start time: 2024-01-02T20:09:04.126768084Z
2024-01-02 20:09:04.140 INFO  (main) [] o.a.s.s.CoreContainerProvider Solr started with "-XX:+CrashOnOutOfMemoryError" that will crash on any OutOfMemoryError exception. The cause of the OOME will be logged in the crash file at the following path: /opt/bitnami/solr/logs/jvm_crash_3445.log
2024-01-02 20:09:04.187 INFO  (main) [] o.a.s.s.CoreContainerProvider Solr Home: /opt/bitnami/solr/server/solr (source: system property: solr.solr.home)
2024-01-02 20:09:04.212 INFO  (main) [] o.a.s.c.SolrXmlConfig Loading solr.xml from /opt/bitnami/solr/server/solr/solr.xml
2024-01-02 20:09:04.302 INFO  (main) [] o.a.s.c.SolrResourceLoader Added 1 libs to classloader, from paths: [/opt/bitnami/solr/lib]
2024-01-02 20:09:05.937 INFO  (main) [] o.a.s.u.t.SimplePropagator Always-on trace id generation enabled.
2024-01-02 20:09:06.565 WARN  (main) [] o.a.s.u.StartupLoggingUtils Jetty request logging enabled. Will retain logs for last 3 days. See chapter "Configuring Logging" in reference guide for how to configure.
2024-01-02 20:09:06.574 INFO  (main) [] o.a.s.c.CoreContainer Initializing authorization plugin: solr.RuleBasedAuthorizationPlugin
2024-01-02 20:09:06.590 INFO  (main) [] o.a.s.c.CoreContainer Initializing authentication plugin: solr.BasicAuthPlugin
2024-01-02 20:09:06.601 WARN  (main) [] o.a.s.c.CoreContainer Solr authentication is enabled, but SSL is off.  Consider enabling SSL to protect user credentials and data with encryption.
2024-01-02 20:09:07.022 INFO  (main) [] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /opt/bitnami/solr/server/solr
2024-01-02 20:09:07.023 INFO  (main) [] o.a.s.c.CorePropertiesLocator Cores are: [test_core_1]
2024-01-02 20:09:07.154 INFO  (coreLoadExecutor-11-thread-1) [ x:test_core_1] o.a.s.c.SolrConfig Using Lucene MatchVersion: 9.8.0
2024-01-02 20:09:07.410 INFO  (coreLoadExecutor-11-thread-1) [ x:test_core_1] o.a.s.s.IndexSchema Schema name=default-config
2024-01-02 20:09:07.676 WARN  (main) [] o.g.j.m.i.MessagingBinders A class javax.activation.DataSource for a default provider MessageBodyWriter<javax.activation.DataSource> was not found. The provider is not available.
2024-01-02 20:09:08.051 INFO  (coreLoadExecutor-11-thread-1) [ x:test_core_1] o.a.s.s.IndexSchema Loaded schema default-config/1.6 with uniqueid field id
2024-01-02 20:09:08.052 INFO  (coreLoadExecutor-11-thread-1) [ x:test_core_1] o.a.s.c.CoreContainer Creating SolrCore 'test_core_1' using configuration from instancedir /opt/bitnami/solr/server/solr/test_core_1, trusted=true
2024-01-02 20:09:08.123 INFO  (coreLoadExecutor-11-thread-1) [ x:test_core_1] o.a.s.c.SolrCore Opening new SolrCore at [/opt/bitnami/solr/server/solr/test_core_1], dataDir=[/opt/bitnami/solr/server/solr/test_core_1/data/]
2024-01-02 20:09:08.153 INFO  (coreLoadExecutor-11-thread-1) [ x:test_core_1] o.a.s.c.SolrCore CLOSING SolrCore org.apache.solr.core.SolrCore@4f473847 test_core_1
2024-01-02 20:09:08.155 INFO  (coreLoadExecutor-11-thread-1) [ x:test_core_1] o.a.s.m.SolrMetricManager Closing metric reporters for registry=solr.core.test_core_1 tag=SolrCore@4f473847
2024-01-02 20:09:08.166 ERROR (coreLoadExecutor-11-thread-1) [ x:test_core_1] o.a.s.c.SolrCore Exception cleanupOldIndexDirectories => java.security.AccessControlException: access denied ("java.io.FilePermission" "/bitnami/solr/server/solr/test_core_1/data" "read")
        at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
java.security.AccessControlException: access denied ("java.io.FilePermission" "/bitnami/solr/server/solr/test_core_1/data" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:1068) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:416) ~[?:?]
        at java.lang.SecurityManager.checkRead(SecurityManager.java:756) ~[?:?]
```

Is this possibly something to do with how the VM's disk is being set up?

**Comment by jotamartos** [comment]
I'm trying to reproduce the issue but I couldn't do so. I just launched a fresh VM and ran these commands 

```
$ export SOLR_AUTH_TYPE="basic"
$ export SOLR_AUTHENTICATION_OPTS="-Dbasicauth=admin:t4o=40k8gRDo"
$ sudo -E su solr -c "solr create -c jota1"
WARNING: Using _default configset with data driven schema functionality. NOT RECOMMENDED for production use.
         To turn off: bin/solr config -c jota1 -p 8983 -action set-user-property -property update.autoCreateFields -value false

Created new core 'jota1'
```

After that, I restarted Solr, checked the log file and found no errors.

```
$ cat /opt/bitnami/solr/logs/solr.log
2024-01-08 11:51:52.394 INFO  (main) [] o.e.j.s.Server jetty-10.0.17; built: 2023-10-09T18:22:21.150Z; git: af15f12297adf5c5083e1f2f8f4c5974438bca25; jvm 17.0.9+11-LTS
2024-01-08 11:51:52.742 WARN  (main) [] o.e.j.u.DeprecationWarning Using @Deprecated Class org.eclipse.jetty.servlet.listener.ELContextCleaner
2024-01-08 11:51:52.769 INFO  (main) [] o.a.s.s.CoreContainerProvider Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
2024-01-08 11:51:52.777 INFO  (main) [] o.a.s.s.CoreContainerProvider  ___      _       Welcome to Apache Solr™ version 9.4.0
2024-01-08 11:51:52.777 INFO  (main) [] o.a.s.s.CoreContainerProvider / __| ___| |_ _   Starting in standalone mode on port 8983
2024-01-08 11:51:52.778 INFO  (main) [] o.a.s.s.CoreContainerProvider \__ \/ _ \ | '_|  Install dir: /opt/bitnami/solr
2024-01-08 11:51:52.778 INFO  (main) [] o.a.s.s.CoreContainerProvider |___/\___/_|_|    Start time: 2024-01-08T11:51:52.778467700Z
2024-01-08 11:51:52.782 INFO  (main) [] o.a.s.s.CoreContainerProvider Solr started with "-XX:+CrashOnOutOfMemoryError" that will crash on any OutOfMemoryError exception. The cause of the OOME will be logged in the crash file at the following path: /opt/bitnami/solr/logs/jvm_crash_2817.log
2024-01-08 11:51:52.805 INFO  (main) [] o.a.s.s.CoreContainerProvider Solr Home: /opt/bitnami/solr/server/solr (source: system property: solr.solr.home)
2024-01-08 11:51:52.820 INFO  (main) [] o.a.s.c.SolrXmlConfig Loading solr.xml from /opt/bitnami/solr/server/solr/solr.xml
2024-01-08 11:51:52.859 INFO  (main) [] o.a.s.c.SolrResourceLoader Added 1 libs to classloader, from paths: [/opt/bitnami/solr/lib]
2024-01-08 11:51:53.779 INFO  (main) [] o.a.s.u.t.SimplePropagator Always-on trace id generation enabled.
2024-01-08 11:51:54.174 WARN  (main) [] o.a.s.u.StartupLoggingUtils Jetty request logging enabled. Will retain logs for last 3 days. See chapter "Configuring Logging" in reference guide for how to configure.
2024-01-08 11:51:54.180 INFO  (main) [] o.a.s.c.CoreContainer Initializing authorization plugin: solr.RuleBasedAuthorizationPlugin
2024-01-08 11:51:54.188 INFO  (main) [] o.a.s.c.CoreContainer Initializing authentication plugin: solr.BasicAuthPlugin
2024-01-08 11:51:54.195 WARN  (main) [] o.a.s.c.CoreContainer Solr authentication is enabled, but SSL is off.  Consider enabling SSL to protect user credentials and data with encryption.
2024-01-08 11:51:54.452 INFO  (main) [] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /opt/bitnami/solr/server/solr
2024-01-08 11:51:54.453 INFO  (main) [] o.a.s.c.CorePropertiesLocator Cores are: [jota1]
2024-01-08 11:51:54.536 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.c.SolrConfig Using Lucene MatchVersion: 9.8.0
2024-01-08 11:51:54.741 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.s.IndexSchema Schema name=default-config
2024-01-08 11:51:54.926 WARN  (main) [] o.g.j.m.i.MessagingBinders A class javax.activation.DataSource for a default provider MessageBodyWriter<javax.activation.DataSource> was not found. The provider is not available.
2024-01-08 11:51:55.124 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.s.IndexSchema Loaded schema default-config/1.6 with uniqueid field id
2024-01-08 11:51:55.124 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.c.CoreContainer Creating SolrCore 'jota1' using configuration from instancedir /opt/bitnami/solr/server/solr/jota1, trusted=true
2024-01-08 11:51:55.186 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.c.SolrCore Opening new SolrCore at [/opt/bitnami/solr/server/solr/jota1], dataDir=[/opt/bitnami/solr/server/solr/jota1/data/]
2024-01-08 11:51:55.483 INFO  (main) [] o.a.s.j.SolrRequestAuthorizer Creating a new SolrRequestAuthorizer
2024-01-08 11:51:55.786 INFO  (main) [] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@6928f576{solr-jetty-context.xml,/solr,file:///opt/bitnami/solr/server/solr-webapp/webapp/,AVAILABLE}{/opt/bitnami/solr/server/solr-webapp/webapp}
2024-01-08 11:51:55.805 INFO  (main) [] o.e.j.s.RequestLogWriter Opened /opt/bitnami/solr/logs/2024_01_08.request.log
2024-01-08 11:51:55.818 INFO  (main) [] o.e.j.s.AbstractConnector Started ServerConnector@4c4d27c8{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:8983}
2024-01-08 11:51:55.819 INFO  (main) [] o.e.j.s.Server Started Server@56ace400{STARTING}[10.0.17,sto=0] @4721ms
2024-01-08 11:51:56.081 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.j.SolrRequestAuthorizer Creating a new SolrRequestAuthorizer
2024-01-08 11:51:56.110 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.u.UpdateHandler Using UpdateLog implementation: org.apache.solr.update.UpdateLog
2024-01-08 11:51:56.110 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.u.UpdateLog Initializing UpdateLog: dataDir= defaultSyncLevel=FLUSH numRecordsToKeep=100 maxNumLogsToKeep=10 numVersionBuckets=65536
2024-01-08 11:51:56.125 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.u.CommitTracker Hard AutoCommit: if uncommitted for 15000ms;
2024-01-08 11:51:56.125 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.u.CommitTracker Soft AutoCommit: if uncommitted for 3000ms;
2024-01-08 11:51:56.211 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.r.ManagedResourceStorage File-based storage initialized to use dir: /opt/bitnami/solr/server/solr/jota1/conf
2024-01-08 11:51:56.227 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.s.DirectSolrSpellChecker init: {maxEdits=2, minPrefix=1, maxInspections=5, minQueryLength=4, accuracy=0.5, maxQueryFrequency=0.01, name=default, field=_text_, classname=solr.DirectSolrSpellChecker, distanceMeasure=internal}
2024-01-08 11:51:56.236 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.h.ReplicationHandler Commits will be reserved for 10000 ms
2024-01-08 11:51:56.240 INFO  (coreLoadExecutor-11-thread-1) [ x:jota1] o.a.s.u.UpdateLog Could not find max version in index or recent updates, using new clock 1787522938296074240
2024-01-08 11:51:56.244 INFO  (searcherExecutor-13-thread-1-processing-jota1) [ x:jota1] o.a.s.c.QuerySenderListener QuerySenderListener done.
2024-01-08 11:51:56.244 INFO  (searcherExecutor-13-thread-1-processing-jota1) [ x:jota1] o.a.s.h.c.SpellCheckComponent Loading spell index for spellchecker: default
2024-01-08 11:51:56.251 INFO  (searcherExecutor-13-thread-1-processing-jota1) [ x:jota1] o.a.s.c.SolrCore Registered new searcher autowarm time: 0 ms
```

I'll try to reproduce this issue with a Google's cloud instance and will update this ticket.

**Comment by s-paquette** [comment]
So in looking this over, I think I've found the problem. The solr script in bin for this image doesn't result in a command which includes `-Dsolr.data.home`. 

solr        2567       1  6 19:17 ?        00:00:20 /opt/bitnami/java/bin/java -server -Xms512m -Xmx6428m -XX:+UseG1GC -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+UseLargePages -XX:+AlwaysPreTouch -XX:+ExplicitGCInvokesConcurrent -Xlog:gc*:file=/opt/bitnami/solr/logs/solr_gc.log:time,uptime:filecount=9,filesize=20M -Dsolr.jetty.inetaccess.includes= -Dsolr.jetty.inetaccess.excludes= -Dsolr.log.dir=/opt/bitnami/solr/logs -Djetty.port=8983 -DSTOP.PORT=7983 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -XX:-OmitStackTraceInFastThrow -XX:+CrashOnOutOfMemoryError -XX:ErrorFile=/opt/bitnami/solr/logs/jvm_crash_%p.log -Djetty.home=/opt/bitnami/solr/server -Dsolr.solr.home=/opt/bitnami/solr/server/solr -Dsolr.install.dir=/opt/bitnami/solr -Dsolr.install.symDir=/opt/bitnami/solr -Dsolr.default.confdir=/opt/bitnami/solr/server/solr/configsets/_default/conf -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dsolr.jetty.host=0.0.0.0 -Xss256k -XX:CompileCommand=exclude,com.github.benmanes.caffeine.cache.BoundedLocalCache::put -DdisableAdminUI=false -Dsolr.log.muteconsole -jar start.jar --module=http --module=requestlog --module=gzip

Prior versions produce a command which has this entry, though if solr.in.sh isn't altered to provide a value it's blank:

solr      173827       1  0 Dec01 ?        02:53:36 /opt/bitnami/java/bin/java -server -Xms1024m -Xmx4096m -XX:+UseG1GC -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+UseLargePages -XX:+AlwaysPreTouch -XX:+ExplicitGCInvokesConcurrent -Xlog:gc*:file=/opt/bitnami/solr/logs/solr_gc.log:time,uptime:filecount=9,filesize=20M -Dsolr.jetty.inetaccess.includes= -Dsolr.jetty.inetaccess.excludes= -Dsolr.log.dir=/opt/bitnami/solr/logs -Djetty.port=8983 -DSTOP.PORT=7983 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -XX:-OmitStackTraceInFastThrow -XX:OnOutOfMemoryError=/opt/bitnami/solr/bin/oom_solr.sh 8983 /opt/bitnami/solr/logs -Djetty.home=/opt/bitnami/solr/server -Dsolr.solr.home=/opt/bitnami/solr/server/solr **-Dsolr.data.home=** -Dsolr.install.dir=/opt/bitnami/solr -Dsolr.default.confdir=/opt/bitnami/solr/server/solr/configsets/_default/conf -Dsolr.jetty.host=0.0.0.0 -Xss256k -Dsolr.jetty.keystore=etc/solr-ssl.keystore.jks -Dsolr.jetty.keystore.type=JKS -Dsolr.jetty.truststore=etc/solr-ssl.keystore.jks -Dsolr.jetty.truststore.type=JKS -Dsolr.jetty.ssl.verifyClientHostName=HTTPS -Dsolr.jetty.ssl.needClientAuth=false -Dsolr.jetty.ssl.wantClientAuth=false -Djavax.net.ssl.keyStore=etc/solr-ssl.keystore.jks -Djavax.net.ssl.keyStoreType=JKS -Dsolr.ssl.checkPeerName=false -Djavax.net.ssl.trustStore=etc/solr-ssl.keystore.jks -Djavax.net.ssl.trustStoreType=JKS -Dsolr.jetty.https.port=8983 -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.PreemptiveBasicAuthClientBuilderFactory -Dbasicauth=xxx:xxxxxxx -Djava.security.manager -Djava.security.policy=/opt/bitnami/solr/server/etc/security.policy -Djava.security.properties=/opt/bitnami/solr/server/etc/security.properties -Dsolr.internal.network.permission=* -DdisableAdminUI=false -Dsolr.log.muteconsole -jar start.jar --module=https --lib=/opt/bitnami/solr/server/solr-webapp/webapp/WEB-INF/lib/* --module=requestlog --module=gzip


If I edit `/bin/solr` to add `-Dsolr.data.home=${SOLR_DATA_HOME:-}` back in, it works. I would have assumed Solr would fall back to `SOLR_HOME/data` but it seems to not be doing that in the case of a Google VM launch.
