### ISSUE TITLE
GITLAB Bitnami package for GitLab CE 16.7.0-ce.0-0

### ISSUE THREAD

**Issue by sidnintv** [bitnami/vms#1401]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

b96a578a-c652-e646-366d-5c05d2cc4972

### bndiagnostic output

===== Begin of bndiagnostic tool output =====

 
    ? Resources: Found possible issues
    ? Connectivity: Found possible issues
    ✓ Processes: No issues found
 

 
[Resources]

Your instance has little available RAM memory.
```
 total used free shared buff/cache available Mem: 3873 3203 145 45 524 400 Swap: 
8191 1080 7111
```
You could try to increase your instance's memory. Please check your cloud 
provider's documentation for more information.

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the 
Press [Enter] to continue:
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/
 

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

everything all right

### Describe your issue as much as you can

Changed the path to the local storage for LFS. The storage was mounted over ssh protocol with read, write and execute rights for the git user. After applying the sudo gitlab-ctl reconfigure command, an error occurred. 

Error:

```
bitnami@ip-172-26-0-237:/$ sudo gitlab-ctl reconfigure
[2024-02-05T22:51:47+00:00] INFO: Started Cinc Zero at chefzero://localhost:1 with repository at /opt/gitlab/embedded (One version per cookbook)
Cinc Client, version 17.10.0
Patents: https://www.chef.io/patents
Infra Phase starting
[2024-02-05T22:51:47+00:00] INFO: *** Cinc Client 17.10.0 ***
[2024-02-05T22:51:47+00:00] INFO: Platform: x86_64-linux
[2024-02-05T22:51:47+00:00] INFO: Cinc-client pid: 36262
[2024-02-05T22:51:48+00:00] INFO: Setting the run_list to ["recipe[gitlab]"] from CLI options
[2024-02-05T22:51:48+00:00] INFO: Run List is [recipe[gitlab]]
[2024-02-05T22:51:48+00:00] INFO: Run List expands to [gitlab]
[2024-02-05T22:51:48+00:00] INFO: Starting Cinc Client Run for ip-172-26-0-237.eu-west-3.compute.internal
[2024-02-05T22:51:48+00:00] INFO: Running start handlers
[2024-02-05T22:51:48+00:00] INFO: Start handlers complete.
Resolving cookbooks for run list: ["gitlab"]
[2024-02-05T22:51:49+00:00] INFO: Loading cookbooks [gitlab@0.0.1, package@0.1.0, logrotate@0.1.0, postgresql@0.1.0, redis@0.1.0, monitoring@0.1.0, registry@0.1.0, mattermost@0.1.0, consul@0.1.0, gitaly@0.1.0, praefect@0.1.0, gitlab-kas@0.1.0, gitlab-pages@0.1.0, letsencrypt@0.1.0, nginx@0.1.0, runit@5.1.7, acme@4.1.6, crond@0.1.0]
Synchronizing cookbooks:
  - logrotate (0.1.0)
  - redis (0.1.0)
  - registry (0.1.0)
  - mattermost (0.1.0)
  - gitaly (0.1.0)
  - praefect (0.1.0)
  - gitlab-kas (0.1.0)
  - gitlab-pages (0.1.0)
  - nginx (0.1.0)
  - runit (5.1.7)
  - acme (4.1.6)
  - crond (0.1.0)
[2024-02-05T22:51:49+00:00] INFO: Storing updated cookbooks/package/libraries/storage_directory_helper.rb in the cache.
  - package (0.1.0)
  - postgresql (0.1.0)
  - consul (0.1.0)
  - gitlab (0.0.1)
  - monitoring (0.1.0)
  - letsencrypt (0.1.0)
Installing cookbook gem dependencies:
Compiling cookbooks...
/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/helpers/selinux_distro_helper.rb:2: warning: already initialized constant SELinuxDistroHelper::REDHAT_RELEASE_FILE
/opt/gitlab/embedded/cookbooks/package/libraries/helpers/selinux_distro_helper.rb:2: warning: previous definition of REDHAT_RELEASE_FILE was here
/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/helpers/selinux_distro_helper.rb:3: warning: already initialized constant SELinuxDistroHelper::OS_RELEASE_FILE
/opt/gitlab/embedded/cookbooks/package/libraries/helpers/selinux_distro_helper.rb:3: warning: previous definition of OS_RELEASE_FILE was here
/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/helpers/secrets_helper.rb:4: warning: already initialized constant SecretsHelper::SECRETS_FILE
/opt/gitlab/embedded/cookbooks/package/libraries/helpers/secrets_helper.rb:4: warning: previous definition of SECRETS_FILE was here
/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/helpers/secrets_helper.rb:5: warning: already initialized constant SecretsHelper::SECRETS_FILE_CHEF_ATTR
/opt/gitlab/embedded/cookbooks/package/libraries/helpers/secrets_helper.rb:5: warning: previous definition of SECRETS_FILE_CHEF_ATTR was here
/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/helpers/secrets_helper.rb:6: warning: already initialized constant SecretsHelper::SKIP_GENERATE_SECRETS_CHEF_ATTR
/opt/gitlab/embedded/cookbooks/package/libraries/helpers/secrets_helper.rb:6: warning: previous definition of SKIP_GENERATE_SECRETS_CHEF_ATTR was here
/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/gitlab_cluster.rb:16: warning: already initialized constant GitlabCluster::CONFIG_PATH
/opt/gitlab/embedded/cookbooks/package/libraries/gitlab_cluster.rb:16: warning: previous definition of CONFIG_PATH was here
/opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/gitlab_cluster.rb:17: warning: already initialized constant GitlabCluster::JSON_FILE
/opt/gitlab/embedded/cookbooks/package/libraries/gitlab_cluster.rb:17: warning: previous definition of JSON_FILE was here
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
Loading Cinc Auditor profile files:
Loading Cinc Auditor input files:
Loading Cinc Auditor waiver files:
[2024-02-05T22:51:50+00:00] INFO: Generating default secrets
[2024-02-05T22:51:52+00:00] INFO: Generating /etc/gitlab/gitlab-secrets.json file
Recipe: gitlab::default
  * directory[/etc/gitlab] action create (up to date)
[2024-02-05T22:51:53+00:00] WARN: gitlab-rails does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: Selected systemd because /run/systemd/system/ exists
[2024-02-05T22:51:53+00:00] WARN: gitlab-shell does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: gitlab-sshd does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: logrotate does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: logrotate does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: puma does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: gitlab-rails does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: gitlab-shell does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: gitlab-workhorse does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: gitlab-pages does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: gitlab-kas does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: gitaly does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: mailroom does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: gitaly does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: postgresql does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:53+00:00] WARN: postgresql does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: gitlab-kas does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: puma does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: sidekiq does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: gitlab-workhorse does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: node-exporter does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: gitlab-exporter does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: redis-exporter does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: prometheus does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: alertmanager does not have a log_group or default logdir mode defined. Setting to 0700.
[2024-02-05T22:51:54+00:00] WARN: postgres-exporter does not have a log_group or default logdir mode defined. Setting to 0700.
  Converging 274 resources
  * directory[/etc/gitlab] action create (up to date)
  * directory[Create /var/opt/gitlab] action create (up to date)
  * directory[Create /var/log/gitlab] action create (up to date)
  * directory[/opt/gitlab/embedded/etc] action create (up to date)
  * template[/opt/gitlab/embedded/etc/gitconfig] action create (up to date)
Recipe: gitlab::web-server
  * account[Webserver user and group] action create
    * group[Webserver user and group] action create (up to date)
    * linux_user[Webserver user and group] action create (up to date)
     (up to date)
Recipe: gitlab::users
  * directory[/var/opt/gitlab] action create (up to date)
  * account[GitLab user and group] action create
    * group[GitLab user and group] action create (up to date)
    * linux_user[GitLab user and group] action create (up to date)
     (up to date)
  * template[/var/opt/gitlab/.gitconfig] action create (up to date)
  * directory[/var/opt/gitlab/.bundle] action create (up to date)
Recipe: gitlab::gitlab-rails
  * storage_directory[/var/opt/gitlab/git-data] action create
    * ruby_block[directory resource: /var/opt/gitlab/git-data] action run (skipped due to not_if)
     (up to date)
  * storage_directory[/var/opt/gitlab/git-data/repositories] action create
    * ruby_block[directory resource: /var/opt/gitlab/git-data/repositories] action run (skipped due to not_if)
     (up to date)
Recipe: gitlab::rails_pages_shared_path
  * storage_directory[/var/opt/gitlab/gitlab-rails/shared] action create
    * ruby_block[directory resource: /var/opt/gitlab/gitlab-rails/shared] action run (skipped due to not_if)
     (up to date)
  * storage_directory[/var/opt/gitlab/gitlab-rails/shared/pages] action create
    * ruby_block[directory resource: /var/opt/gitlab/gitlab-rails/shared/pages] action run (skipped due to not_if)
     (up to date)
Recipe: gitlab::gitlab-rails
  * storage_directory[/var/opt/gitlab/gitlab-rails/shared/artifacts] action create
    * ruby_block[directory resource: /var/opt/gitlab/gitlab-rails/shared/artifacts] action run (skipped due to not_if)
     (up to date)
  * storage_directory[/var/opt/gitlab/gitlab-rails/shared/external-diffs] action create
    * ruby_block[directory resource: /var/opt/gitlab/gitlab-rails/shared/external-diffs] action run (skipped due to not_if)
     (up to date)
  * storage_directory[/mnt/lfs/lfs-objects] action create
    * ruby_block[directory resource: /mnt/lfs/lfs-objects] action run
      
      ================================================================================
      Error executing action `run` on resource 'ruby_block[directory resource: /mnt/lfs/lfs-objects]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of chgrp git /mnt/lfs/lfs-objects ----
      STDOUT: 
      STDERR: chgrp: changing group of '/mnt/lfs/lfs-objects': Permission denied
      ---- End output of chgrp git /mnt/lfs/lfs-objects ----
      Ran chgrp git /mnt/lfs/lfs-objects returned 1
      
      Cookbook Trace: (most recent call first)
      ----------------------------------------
      /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:35:in `run_command'
      /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:52:in `ensure_permissions_set'
      /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb:42:in `block (3 levels) in class_from_file'
      /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb:36:in `block in class_from_file'
      
      Resource Declaration:
      ---------------------
      # In /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb
      
       36:   ruby_block "directory resource: #{new_resource.path}" do
       37:     block do
       38:       # Ensure the directory exists
       39:       storage_helper.ensure_directory_exists(new_resource.path)
       40: 
       41:       # Ensure the permissions are set
       42:       storage_helper.ensure_permissions_set(new_resource.path)
       43: 
       44:       # Error out if we have not achieved the target permissions
       45:       storage_helper.validate!(new_resource.path)
       46:     end
       47:     not_if { storage_helper.validate(new_resource.path) }
       48:   end
       49: end
      
      Compiled Resource:
      ------------------
      # Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb:36:in `block in class_from_file'
      
      ruby_block("directory resource: /mnt/lfs/lfs-objects") do
        action [:run]
        default_guard_interpreter :default
        declared_type :ruby_block
        cookbook_name "gitlab"
        recipe_name "gitlab-rails"
        block #<Proc:0x00007fd36dac5d58 /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb:37>
        not_if { #code block }
      end
      
      System Info:
      ------------
      chef_version=17.10.0
      platform=debian
      platform_version=11
      ruby=ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
      program_name=/opt/gitlab/embedded/bin/cinc-client
      executable=/opt/gitlab/embedded/bin/cinc-client
      
    
    ================================================================================
    Error executing action `create` on resource 'storage_directory[/mnt/lfs/lfs-objects]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    ruby_block[directory resource: /mnt/lfs/lfs-objects] (gitlab::gitlab-rails line 36) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of chgrp git /mnt/lfs/lfs-objects ----
    STDOUT: 
    STDERR: chgrp: changing group of '/mnt/lfs/lfs-objects': Permission denied
    ---- End output of chgrp git /mnt/lfs/lfs-objects ----
    Ran chgrp git /mnt/lfs/lfs-objects returned 1
    
    Cookbook Trace: (most recent call first)
    ----------------------------------------
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:35:in `run_command'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/libraries/storage_directory_helper.rb:52:in `ensure_permissions_set'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb:42:in `block (3 levels) in class_from_file'
    /opt/gitlab/embedded/cookbooks/cache/cookbooks/package/resources/storage_directory.rb:36:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/gitlab-rails.rb
    
     83:   storage_directory dir_name do
     84:     owner gitlab_user
     85:     group gitlab_group
     86:     mode '0700'
     87:   end
     88: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/gitlab-rails.rb:83:in `block in from_file'
    
    storage_directory("/mnt/lfs/lfs-objects") do
      action [:create]
      default_guard_interpreter :default
      declared_type :storage_directory
      cookbook_name "gitlab"
      recipe_name "gitlab-rails"
      owner "git"
      group "git"
      mode "0700"
      path "/mnt/lfs/lfs-objects"
    end
    
    System Info:
    ------------
    chef_version=17.10.0
    platform=debian
    platform_version=11
    ruby=ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
    program_name=/opt/gitlab/embedded/bin/cinc-client
    executable=/opt/gitlab/embedded/bin/cinc-client
    
[2024-02-05T22:51:55+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2024-02-05T22:51:55+00:00] ERROR: Running exception handlers
There was an error running gitlab-ctl reconfigure:

storage_directory[/mnt/lfs/lfs-objects] (gitlab::gitlab-rails line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: ruby_block[directory resource: /mnt/lfs/lfs-objects] (gitlab::gitlab-rails line 36) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of chgrp git /mnt/lfs/lfs-objects ----
STDOUT: 
STDERR: chgrp: changing group of '/mnt/lfs/lfs-objects': Permission denied
---- End output of chgrp git /mnt/lfs/lfs-objects ----
Ran chgrp git /mnt/lfs/lfs-objects returned 1

Running handlers complete
[2024-02-05T22:51:55+00:00] ERROR: Exception handlers complete
Infra Phase failed. 0 resources updated in 08 seconds
[2024-02-05T22:51:55+00:00] FATAL: Stacktrace dumped to /opt/gitlab/embedded/cookbooks/cache/cinc-stacktrace.out
[2024-02-05T22:51:55+00:00] FATAL: ---------------------------------------------------------------------------------------
[2024-02-05T22:51:55+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2024-02-05T22:51:55+00:00] FATAL: ---------------------------------------------------------------------------------------
[2024-02-05T22:51:55+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: storage_directory[/mnt/lfs/lfs-objects] (gitlab::gitlab-rails line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: ruby_block[directory resource: /mnt/lfs/lfs-objects] (gitlab::gitlab-rails line 36) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of chgrp git /mnt/lfs/lfs-objects ----
STDOUT: 
STDERR: chgrp: changing group of '/mnt/lfs/lfs-objects': Permission denied
---- End output of chgrp git /mnt/lfs/lfs-objects ----
Ran chgrp git /mnt/lfs/lfs-objects returned 1
```

Rights cannot be changed on a disk mounted using the sshfs protocol, since this is a remote disk management system from the hetzner provider, access to it via sshfs and webdav.

**Comment by jotamartos** [comment]
Hi @sidnintv,

Thank you for using Bitnami. For the Gitlab solution, we use the system packages they provide to install the application. As this issue is very specific to it, I suggest you ask in the official forums of the application and check its documentation to get more information about the issue and how to solve it. 

Thanks

**Comment by sidnintv** [comment]
Hi @jotamartos,

I have solved the problem.
It was necessary to disable the management of storage directories:
https://docs.gitlab.com/omnibus/settings/configuration.html#disable-storage-directories-management

Thanks
