### ISSUE TITLE
[WordPress] AWS EC2 t3a.medium Wordpress/MariaDb WILL NOT start

### ISSUE THREAD

**Issue by NEOROMAH** [bitnami/vms#1417]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

ecb9990c-06e0-6959-2c06-b8fab0d12ba6

### bndiagnostic output

The bndiagnostic tool has finished searching for errors and has found some
issues that might be related to yours. The output will be shown on the next
page:

Press [Enter] to continue:

===== Begin of bndiagnostic tool output =====

    ✓ Resources: No issues found
    ? Connectivity: Found possible issues
    ? Mariadb: Found possible issues
    ? Processes: Found possible issues
    ? Wordpress: Found possible issues
    ✓ Apache: No issues found
    ✓ Php: No issues found

[Connectivity]

Server ports 22, 80 and/or 443 are not publicly accessible. Please check the
following guide to open server ports for remote access:

https://docs.bitnami.com/general/faq/administration/use-firewall/

[Mariadb]

Press [Enter] to continue:
Found recent error messages in the MariaDB error log:
```
2024-02-19 13:54:45 0 [ERROR] Aborting

```
Please check the following guide to troubleshoot MariaDB issues:

https://docs.bitnami.com/aws/apps/wordpress/troubleshooting/debug-errors-m
ariadb/

Some files don't have the expected permissions. Please check the following
guide:

https://docs.bitnami.com/general/how-to/troubleshoot-permission-issues/

[Processes]

One or more component's processes are not running:
```
mariadb not running
```
You can try to restart the process with the following command:
Press [Enter] to continue:

 $ sudo /opt/bitnami/ctlscript.sh start COMPONENT_NAME

[Wordpress]

Some files don't have the expected permissions Please check the following guide:

https://docs.bitnami.com/general/apps/wordpress/administration/understand-
file-permissions/

Found recent WordPress plugin related error messages in the Apache error log.
```
[Mon Feb 19 15:46:16.098268 2024] [proxy_fcgi:error] [pid 3168:tid
140565571999488] [client **ip_address**:33046] AH01071: Got error 'PHP message:
PHP Fatal error: Uncaught Error: Call to undefined function wp_cache_get() in
/opt/bitnami/wordpress/wp-includes/option.php:599
Stack trace:
#0 /opt/bitnami/wordpress/wp-includes/option.php(164): wp_load_alloptions()
#1 /opt/bitnami/wordpress/wp-includes/l10n.php(63): get_option()
#2 /opt/bitnami/wordpress/wp-includes/l10n.php(156): get_locale()
#
```
Please check the following guide to deactivate plugins:
Press [Enter] to continue:

https://developer.wordpress.org/cli/commands/plugin/deactivate/

===== End of bndiagnostic tool output =====

### bndiagnostic was not useful. Could you please tell us why?

I followed all the suggestions made didnt work

### Describe your issue as much as you can

Have tried several times to reboot the instance via AWS and also SSH. Followed Bitnami troubleshooting guide with no joy. 

But after spending all day I cannot get mariadb to start.

Ports via security group at set to 0.0.0.0/0 on SSH,https,HTTP on ports 22, 80, 443 and are as provided by: WordPress Certified by Bitnami and Automattic-6.1.1-53-r54 on Debian 11-AutogenByAWSMP--1

The site has been working very fast since March last year. But at 01:55am this morning it dropped off and nothing will restart mariadb.

**Comment by NEOROMAH** [comment]
I would like to add we had another site with same issue last week. MariaDB would not restart, in the end we ditched the instance and relaunched a new one. We setup an alarm on it to reboot. Even that new instance reboots several times a day.

**Comment by NEOROMAH** [comment]
Bit more info after a failed mariadb restart:

2024-02-19 11:27:11 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 4436
2024-02-19 11:27:11 0 [ERROR] mysqld: File '/opt/bitnami/mariadb/data/aria_log_control' not found (Errcode: 13 "Permission denied")
2024-02-19 11:27:11 0 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/opt/bitnami/mariadb/data/aria_log_control'
2024-02-19 11:27:11 0 [ERROR] Plugin 'Aria' init function returned error.
2024-02-19 11:27:11 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
2024-02-19 11:27:11 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 11:27:11 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 11:27:11 0 [ERROR] Plugin 'InnoDB' init function returned error.
2024-02-19 11:27:11 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-02-19 11:27:11 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-19 11:27:11 0 [ERROR] Failed to initialize plugins.
2024-02-19 11:27:11 0 [ERROR] Aborting
2024-02-19 11:28:38 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 4440
2024-02-19 11:28:38 0 [ERROR] mysqld: File '/opt/bitnami/mariadb/data/aria_log_control' not found (Errcode: 13 "Permission denied")
2024-02-19 11:28:38 0 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/opt/bitnami/mariadb/data/aria_log_control'
2024-02-19 11:28:38 0 [ERROR] Plugin 'Aria' init function returned error.
2024-02-19 11:28:38 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
2024-02-19 11:28:38 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 11:28:38 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 11:28:38 0 [ERROR] Plugin 'InnoDB' init function returned error.
2024-02-19 11:28:38 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-02-19 11:28:38 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-19 11:28:38 0 [ERROR] Failed to initialize plugins.
2024-02-19 11:28:38 0 [ERROR] Aborting
2024-02-19 11:47:54 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 2977
2024-02-19 11:47:54 0 [ERROR] mysqld: File '/opt/bitnami/mariadb/data/aria_log_control' not found (Errcode: 13 "Permission denied")
2024-02-19 11:47:54 0 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/opt/bitnami/mariadb/data/aria_log_control'
2024-02-19 11:47:54 0 [ERROR] Plugin 'Aria' init function returned error.
2024-02-19 11:47:54 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
2024-02-19 11:47:55 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 11:47:55 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 11:47:55 0 [ERROR] Plugin 'InnoDB' init function returned error.
2024-02-19 11:47:55 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-02-19 11:47:55 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-19 11:47:55 0 [ERROR] Failed to initialize plugins.
2024-02-19 11:47:55 0 [ERROR] Aborting
2024-02-19 12:00:52 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 3055
2024-02-19 12:00:52 0 [ERROR] mysqld: File '/opt/bitnami/mariadb/data/aria_log_control' not found (Errcode: 13 "Permission denied")
2024-02-19 12:00:52 0 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/opt/bitnami/mariadb/data/aria_log_control'
2024-02-19 12:00:52 0 [ERROR] Plugin 'Aria' init function returned error.
2024-02-19 12:00:52 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
2024-02-19 12:00:52 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 12:00:52 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 12:00:52 0 [ERROR] Plugin 'InnoDB' init function returned error.
2024-02-19 12:00:52 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-02-19 12:00:52 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-19 12:00:52 0 [ERROR] Failed to initialize plugins.
2024-02-19 12:00:52 0 [ERROR] Aborting
2024-02-19 12:26:46 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 3425
2024-02-19 12:26:46 0 [ERROR] mysqld: File '/opt/bitnami/mariadb/data/aria_log_control' not found (Errcode: 13 "Permission denied")
2024-02-19 12:26:46 0 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/opt/bitnami/mariadb/data/aria_log_control'
2024-02-19 12:26:46 0 [ERROR] Plugin 'Aria' init function returned error.
2024-02-19 12:26:46 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
2024-02-19 12:26:46 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 12:26:46 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 12:26:46 0 [ERROR] Plugin 'InnoDB' init function returned error.
2024-02-19 12:26:46 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-02-19 12:26:46 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-19 12:26:46 0 [ERROR] Failed to initialize plugins.
2024-02-19 12:26:46 0 [ERROR] Aborting
2024-02-19 13:53:38 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 4859
2024-02-19 13:53:38 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 13:53:38 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 13:53:38 0 [ERROR] Plugin 'InnoDB' init function returned error.
2024-02-19 13:53:38 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-02-19 13:53:38 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-19 13:53:38 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-02-19 13:53:38 0 [ERROR] Aborting
2024-02-19 13:54:45 0 [Note] Starting MariaDB 10.6.12-MariaDB source revision 4c79e15cc3716f69c044d4287ad2160da8101cdc as process 4862
2024-02-19 13:54:45 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 13:54:45 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
2024-02-19 13:54:45 0 [ERROR] Plugin 'InnoDB' init function returned error.
2024-02-19 13:54:45 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2024-02-19 13:54:45 0 [Note] Plugin 'FEEDBACK' is disabled.
2024-02-19 13:54:45 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2024-02-19 13:54:45 0 [ERROR] Aborting

**Comment by NEOROMAH** [comment]
we now have an issue with a 3rd t3a.medium instance. That's 3 in a week (bitnami/wordpress stack)

Excerpt from daemon.log....

.....
Startup finished in 2.951s (kernel) + 31.931s (userspace) = 34.882s.
Feb 20 10:42:46 ip-172-31-28-30 dhclient[489]: XMT: Solicit on ens5, interval 34290ms.
Feb 20 10:43:21 ip-172-31-28-30 dhclient[489]: XMT: Solicit on ens5, interval 69480ms.
Feb 20 10:44:30 ip-172-31-28-30 dhclient[489]: XMT: Solicit on ens5, interval 111690ms.
Feb 20 10:46:22 ip-172-31-28-30 dhclient[489]: XMT: Solicit on ens5, interval 120730ms.
Feb 20 10:48:23 ip-172-31-28-30 dhclient[489]: XMT: Solicit on ens5, interval 127850ms.
Feb 20 10:50:30 ip-172-31-28-30 dhclient[489]: XMT: Solicit on ens5, interval 116700ms.
Feb 20 10:52:27 ip-172-31-28-30 dhclient[489]: XMT: Solicit on ens5, interval 120690ms.
Feb 20 10:53:56 ip-172-31-28-30 systemd[1]: bitnami.service: A process of this unit has been killed by the OOM killer.
Feb 20 10:53:57 ip-172-31-28-30 bitnami[2015]: 2024-02-20T10:53:57.681Z - info: Saving configuration info to disk
Feb 20 10:53:58 ip-172-31-28-30 bitnami[2015]: 2024-02-20T10:53:58.930Z - info: Stop monitoring services from gonit
Feb 20 10:53:59 ip-172-31-28-30 bitnami[2015]: 2024-02-20T10:53:59.020Z - info: Performing service stop operation for php
Feb 20 10:54:00 ip-172-31-28-30 bitnami[2015]: #033[38;5;6mphp #033[38;5;5m10:54:00.95 #033[0m#033[38;5;2mINFO #033[0m ==> php-fpm stopped
Feb 20 10:54:00 ip-172-31-28-30 bitnami[2015]: 2024-02-20T10:54:00.955Z - info: Performing service stop operation for mariadb
Feb 20 10:54:01 ip-172-31-28-30 bitnami[2015]: #033[38;5;6mmariadb #033[38;5;5m10:54:01.46 #033[0m#033[38;5;2mINFO #033[0m ==> mariadb is not running
Feb 20 10:54:01 ip-172-31-28-30 bitnami[2015]: 2024-02-20T10:54:01.462Z - info: Performing service stop operation for apache
Feb 20 10:54:02 ip-172-31-28-30 bitnami[2015]: #033[38;5;6mapache #033[38;5;5m10:54:02.99 #033[0m#033[38;5;2mINFO #033[0m ==> apache stopped
Feb 20 10:54:02 ip-172-31-28-30 bitnami[2015]: 2024-02-20T10:54:02.993Z - info: Skipping service stop operation for varnish
Feb 20 10:54:03 ip-172-31-28-30 systemd[1]: bitnami.service: Failed with result 'oom-kill'.


oom-kill?

**Comment by jotamartos** [comment]
Hi @NEOROMAH,

> 2024-02-19 12:00:52 0 [ERROR] mysqld: File '/opt/bitnami/mariadb/data/aria_log_control' not found (Errcode: 13 "Permission denied")
> 2024-02-19 12:00:52 0 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/opt/bitnami/mariadb/data/aria_log_control'
> 2024-02-19 12:00:52 0 [ERROR] Plugin 'Aria' init function returned error.
> 2024-02-19 12:00:52 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
> 2024-02-19 12:00:52 0 [ERROR] InnoDB: The data file './ibdata1' must be writable
> 2024-02-19 12:00:52 0 [ERROR] InnoDB: The data file './ibdata1' must be writable

It seems you broke the permissions configuration. I suggest you launch a fresh VM (either in the cloud or locally) and compare the permissions configuration of the /opt/bitnami/mariadb/data folder between the 2 instances. 

Thanks
