### ISSUE TITLE
airflow multitier 

### ISSUE THREAD

**Issue by ipsri** [bitnami/vms#211]
### Platform

Azure

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

4e41de9c-9d79-48d9-ddf3-42e4e3275bd4

### bndiagnostic output

No. 

### bndiagnostic was not useful. Could you please tell us why?

The suggestions are unrelated

### Describe your issue as much as you can

In an airflow dag which contains 10 tables, randomly few tables fail and rest of them are successful. Error from the log is - 
[2022-08-04, 01:43:58 UTC] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/cloudera/cdp/airflow/operators/cdw_operator.py", line 108, in execute
    self.hook.run_cli(hql=self.hql, schema=self.schema, hive_conf=self.hiveconfs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/cloudera/cdp/airflow/hooks/cdw_hook.py", line 204, in run_cli
    sub_process = subprocess.Popen(
  File "/opt/bitnami/python/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/bitnami/python/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'beeline'

why would random tables fail ? what is the issue with the operator ? It started happening suddenly.

**Comment by mdhont** [comment]
Can you give more information on how to reproduce the issue? Did you make any changes to the configuration? If so, which?
