### ISSUE TITLE
[<application>] <Error starting "erpnext" stack>

### ISSUE THREAD

**Issue by unibravo** [bitnami/vms#372]
### Platform

OSX VM

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

bndiagnostic to 0.9.18

### bndiagnostic was not useful. Could you please tell us why?

not related with my issue

### Describe your issue as much as you can

App: bitnami-erpnext-14.2.0-0-osx-x86_64-vm.dmg

Error starting "erpnext" stack
Details:
cannot calculate MAC address: Using fd 12 for I/O notifications
hv_vm_create HV_ERROR (unspecified error)

Model: Apple M1
OS : MacOS BigSur

**Comment by mdhont** [comment]
On which OS version are you running the VM, and what is the Erpnext version?

**Comment by unibravo** [comment]
> On which OS version are you running the VM, and what is the Erpnext version?

MacOS Big Sur Version 11.7

Bitnami ERPNext Version 14.2.0-0
bitnami-erpnext-14.2.0-0-osx-x86_64-vm.dmg

**Comment by unibravo** [comment]
**Same Problem:**
Bitnami ProcessMaker 4.2.35-1

**Apple M1 Chip**
MacOS Big Sur Version 11.7
ProcessMaker version 4.2.35-1
Link: https://bitnami.com/redirect/to/2205763/bitnami-processmaker-4.2.35-1-r01-osx-x86_64-vm.dmg

**Error starting "processmaker" stack**
cannot calculate MAC address: Using fd 12 for I/O notifications
hv_vm_create HV_ERROR (unspecified error)

**Comment by mdhont** [comment]
The OS X VMs do not support ARM architecture so it's not possible to use these solutions on your laptop.

Sorry for the inconvenience.

**Comment by Sertsev** [comment]
I properly added the ERPNext packaged by bitnami. Then started it, then successfully accessed it through the browser using the virtual machine ip address, but When I try to log in with the default 
username: user@example.com 
password: the default password generated and shown on the terminal 
![ERPNext](https://user-images.githubusercontent.com/53481194/214841877-11e20827-1584-46e5-9c63-d82666933efd.PNG)

But It is not logging in
![image](https://user-images.githubusercontent.com/53481194/214842033-3bec2f27-d07c-4111-a909-fe7a26a99b8f.png)

When I checked the browser console, it shows the following error,
`POSThttps://192.168.131.45/
[HTTP/1.1 401 UNAUTHORIZED 388ms]

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 55, in application
    init_request(request)
  File "apps/frappe/frappe/app.py", line 132, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "apps/frappe/frappe/auth.py", line 34, in __init__
    self.set_session()
  File "apps/frappe/frappe/auth.py", line 68, in set_session
    frappe.local.login_manager = LoginManager()
  File "apps/frappe/frappe/auth.py", line 108, in __init__
    if self.login() is False:
  File "apps/frappe/frappe/auth.py", line 133, in login
    self.authenticate(user=user, pwd=pwd)
  File "apps/frappe/frappe/auth.py", line 239, in authenticate
    self.fail("Invalid login credentials", user=_raw_user_name)
  File "apps/frappe/frappe/auth.py", line 292, in fail
    raise frappe.AuthenticationError
frappe.exceptions.AuthenticationError`

What should I do?

**Comment by mdhont** [comment]
I've not been able to investigate it, but could you try using "Administrator" as the username?
