### ISSUE TITLE
[<application>] <title>

### ISSUE THREAD

**Issue by sdpollack** [bitnami/vms#531]
### Describe your issue as much as you can

I am trying to upgrade Redmine from V3.0.3 to 5.0.3 on Windows.  I have been following the instructions at https://docs.bitnami.com/installer/apps/redmine/administration/upgrade/

I have successfully installed a new instance of Bitnami/Redmine on a new server and tested that the empty application works as expected.  I've stopped Appache and have loaded the dump of the source database to the new server and now I'm trying to migrate to upgrade for the changes between versions.

(BTW - It has been hard to figure out what folder to run commands from.  I have been running mostly from E:\Bitnami\redmine-5.0.3-0\apps\redmine\htdocs.  I also found it was helpful to run "ridk enable" since the path did not include any of the ruby tools and nothing worked from the command line.)

I've gotten to the point where I can run "bundle exec rake db:migrate RAILS_ENV=production" but I get this error:

PS E:\bitnami\redmine-5.0.3-0\apps\redmine\htdocs> bundle exec rake db:migrate RAILS_ENV=production --trace
rake aborted!
LoadError: cannot load such file -- E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rouge-3.28.0/lib/rouge/lexers/E:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rouge-3.28.0/lib/rouge/lexers/abap.rb
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rouge-3.28.0/lib/rouge/lexer.rb:532:in `load'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rouge-3.28.0/lib/rouge/lexer.rb:532:in `load_lexer'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rouge-3.28.0/lib/rouge.rb:54:in `block in load_lexers'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rouge-3.28.0/lib/rouge.rb:53:in `each'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rouge-3.28.0/lib/rouge.rb:53:in `load_lexers'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rouge-3.28.0/lib/rouge.rb:69:in `<top (required)>'
E:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/runtime.rb:60:in `require'
E:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
E:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/runtime.rb:55:in `each'
E:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/runtime.rb:55:in `block in require'
E:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/runtime.rb:44:in `each'
E:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/runtime.rb:44:in `require'
E:/Bitnami/redmine-5.0.3-0/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler.rb:174:in `require'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/config/application.rb:18:in `<top (required)>'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/Rakefile:5:in `require'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/Rakefile:5:in `<top (required)>'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
E:/bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
E:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/bin/rake:23:in `load'
E:/Bitnami/redmine-5.0.3-0/apps/redmine/htdocs/vendor/bundle/ruby/2.6.0/bin/rake:23:in `<main>'
PS E:\bitnami\redmine-5.0.3-0\apps\redmine\htdocs>

Here are details on the destination environment:
Environment:
  Redmine version                5.0.3.stable
  Ruby version                   2.6.10-p210 (2022-04-12) [x64-mingw32]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Git                            2.38.0
  Filesystem                     
Redmine plugins:
  no plugin installed

Any ideas about what else to try?

**Comment by mdhont** [comment]
You need to load the Redmine environment to run the db:migrate commands: `:/Bitnami/redmine-5.0.3-0/Use_Redmine.bat`

**Comment by sdpollack** [comment]
Thanks, that did it.
