### ISSUE TITLE
[ERPNext] PDF is not printing

### ISSUE THREAD

**Issue by InfiWits** [bitnami/vms#641]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

dwd

### bndiagnostic was not useful. Could you please tell us why?

NA

### Describe your issue as much as you can

Server Error
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/pdfkit/configuration.py", line 35, in __init__
    with open(self.wkhtmltopdf) as f:
FileNotFoundError: [Errno 2] No such file or directory: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1595, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/print_format.py", line 129, in download_pdf
    pdf_file = frappe.get_print(
  File "apps/frappe/frappe/__init__.py", line 2028, in get_print
    return get_pdf(html, options=pdf_options, output=output)
  File "apps/frappe/frappe/utils/pdf.py", line 38, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
  File "env/lib/python3.10/site-packages/pdfkit/api.py", line 72, in from_string
    r = PDFKit(input, 'string', options=options, toc=toc, cover=cover, css=css,
  File "env/lib/python3.10/site-packages/pdfkit/pdfkit.py", line 45, in __init__
    self.configuration = (Configuration() if configuration is None
  File "env/lib/python3.10/site-packages/pdfkit/configuration.py", line 38, in __init__
    raise IOError('No wkhtmltopdf executable found: "%s"\n'
OSError: No wkhtmltopdf executable found: "b''"
If this file exists please check that this process can read it or you can pass path 

Getting the above error then I have installed wkhtmltopdf but the format is incorrect its not the same format as my Invoice

**Comment by jotamartos** [comment]
Hi @InfiWits,

Thank you for using Bitnami. That error is out of the scope of this support forum and it's related to the application. Please take a look at the app's documentation and its forums to get more information. 

Thanks

**Comment by kabilya** [comment]
I am getting this error still with latest ERP Bitnami image.

**Comment by jotamartos** [comment]
Please remember to install wkhtmltopdf. [We have a guide](https://docs.bitnami.com/google/apps/erpnext/configuration/install-wkhtmltopdf/) that explains how to do it but you can follow the official guides as well. If you continue running into the issue, please contact the upstream project to get more information about it.

**Comment by RustemHesenov** [comment]
**Install wkhtmltopdf Using apt-get**

`sudo apt-get update`

`sudo apt-get -y install wkhtmltopdf`

Source: [](https://chinmayroy.medium.com/how-to-install-wkhtmltopdf-on-ubuntu-b3e56cf7df20)
