### ISSUE TITLE
ELK VM: Security module not working first use

### ISSUE THREAD

**Issue by ubidev** [bitnami/vms#775]
### Describe your issue as much as you can

Hi!

The security module does not work. Error
`Error: Cannot read properties of undefined (reading 'includes')
    at a (http://192.168.100.8/59020/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.13.js:3:2142)
    at http://192.168.100.8/59020/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.4.js:3:45356
    at Object.ka [as useMemo] (http://192.168.100.8/59020/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:398:63914)
    at t.useMemo (http://192.168.100.8/59020/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:374:5744)
    at s (http://192.168.100.8/59020/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.4.js:3:45300)
    at h (http://192.168.100.8/59020/bundles/plugin/securitySolution/8.0.0/securitySolution.chunk.7.js:3:12967)
    at ca (http://192.168.100.8/59020/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:398:59210)
    at Za (http://192.168.100.8/59020/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:398:68953)
    at Js (http://192.168.100.8/59020/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:398:116051)
    at Fu (http://192.168.100.8/59020/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:398:99860)` 

Steps to Reproduce:

- Download [ELK packaged by Bitnami](https://bitnami.com/stack/elk) 8.6.2 OVA as of March 18th 2023
- Import OVA in VMWare
- Boot
- Login
- Set password for bitnami
- Open Browser to vm ip address
- login user:pass
- Click "Explore on my own"
- Click "Security"
- ERROR

The "Observability" and "Analytics" modules WORK OK

Any subsection of the "Security" section of the left side hamburger menu generates the same error.

How can I help troubleshoot this error.

Thanks in advance for taking the time.

**Comment by ubidev** [comment]
![image](https://user-images.githubusercontent.com/14218601/226151871-7cc0a685-6993-43eb-8555-6456e1e099e7.png)
Here is a screenshot of the error

**Comment by mdhont** [comment]
I've reproduced the issue and we will work on a solution. Thank you for reporting it.

**Comment by ubidev** [comment]
You guys are great! Thanks alot

**Comment by gongomgra** [comment]
Hi @ubidev,

I'm moving this ticket to on-hold until we find an issue for it.

**Comment by ubidev** [comment]
Hi !

From "I've reproduced the issue and we will work on a solution" -> In-Progress -> On-Hold... 

Being relatively new here, may I ask what the new state of On-Hold implies regarding the resolution of that reproducible problem ? 

Thanks in advance

**Comment by gongomgra** [comment]
Hi @ubidev,

The "on-hold" status will ensure the ticket is not automatically closed due to inactivity while we are checking the issue on our side.

**Comment by ubidev** [comment]
That's very encouraging!
Muchas Gracias !

**Comment by ubidev** [comment]
Hello again, 
While thjis issue is being addressed for the next release, is there anything I can do to make it work on the current release?

**Comment by ubidev** [comment]
In the mean time, I can confirm that the issue is still present in the new build v8.7.0 of the VM. :-(

**Comment by ubidev** [comment]
Now since I found a much better alternative than waiting for the simplest of courtesies on your part on that issue I will definately stop recommending Bitnami to my students. What a time waster.

**Comment by gongomgra** [comment]
Hi @ubidev,

I'm sorry for the inconveniences you are facing using our products. Unfortunately, our engineering team didn't have time to check this issue yet due to our limited resources. We will keep this ticket in the "on hold" status and post any update here in the future once we have fixed it.

**Comment by khadijadooja** [comment]
hi @ubidev ,
I have the same problem, are you found the solution.

**Comment by ubidev** [comment]
They released a new version of the VM with the same broken major feature. That says alot just there. I moved along, never using bitnami again. Good luck

**Comment by gongomgra** [comment]
Hi @ubidev,

I'm sorry for the inconveniences. I have asked our engineering team to give higher priority to this task whenever possible.
