### ISSUE TITLE
[Jenkins] fails to start, apache related

### ISSUE THREAD

**Issue by mm808** [bitnami/vms#84]
### Platform

AWS

### bndiagnostic ID [know more about bndiagnostic ID](https://docs.bitnami.com/general/how-to/understand-bndiagnostic/)

901bc066-d8db-b673-e6d2-17762f712d09

### bndiagnostic output

Found recent error or warning messages in the Apache error log.
```
[Wed Jul 06 17:45:15.089435 2022] [proxy_http:error] [pid 1478:tid 
140080102283008] [client **ip_address**:43398] AH01114: HTTP: failed to make 
connection to backend: 127.0.0.1, referer: http://jenkins-test.xyz.mywork.com/

[Wed Jul 06 17:55:16.964406 2022] [proxy:error] [pid 2130:tid 140079980848896] 
(111)Connection refused: AH00957: http: attempt to connect to 
**ip_address**:8080 (127.0.0.1:8080) failed
```

### bndiagnostic was not useful. Could you please tell us why?

I have set up and am currently running Bitnami Jenkins servers using same process as this and never had this issue. I don't know why there is a proxy error now.

### Describe your issue as much as you can

It looks from the diagnostic tool that apache fails to run correctly so it doesn't run the jenkins service. I do not understand why there are the following messages in /opt/bitnami/apache2/logs/error_log for each time I run _sudo /opt/bitnami/ctlscript.sh start_

```
[Wed Jul 06 19:06:15.918868 2022] [ssl:warn] [pid 7617:tid 139813558126400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 06 19:06:15.919252 2022] [ssl:warn] [pid 7617:tid 139813558126400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 06 19:06:15.927924 2022] [ssl:warn] [pid 7618:tid 139813558126400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 06 19:06:15.928280 2022] [ssl:warn] [pid 7618:tid 139813558126400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jul 06 19:06:15.930030 2022] [mpm_event:notice] [pid 7618:tid 139813558126400] AH00489: Apache/2.4.54 (Unix) OpenSSL/1.1.1n configured -- resuming normal operations
[Wed Jul 06 19:06:15.930057 2022] [core:notice] [pid 7618:tid 139813558126400] AH00094: Command line: '/opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf'
```

**Comment by jotamartos** [comment]
Hi @mm808,

It seems the gonit process is not working properly, let's try to start the services by running these commands 

```
sudo gonit
sudo gonit status
sudo /opt/bitnami/ctlscript.sh restart
for file in `find /opt/bitnami/scripts/ -name stop.sh`; do sudo $file; done
for file in `find /opt/bitnami/scripts/ -name start.sh`; do sudo $file; done
```

**Comment by mm808** [comment]
Running sudo gonit results in: _Socket file '/var/run/gonit.sock' is not writable_

**Comment by mm808** [comment]
I should make clear the deployment process I am using because I think it is now broken despite working back in March 2022. We have backups of /opt/bitnami/jenkins/home put in S3 every night. For our deployment of a new server we use Terraform to roll out a new EC2 bitnami jenkins giving it the latest AMI version as a parameter. The process also runs a bunch of user-data steps that copy over the backup from S3 among some other config stuff. We had then been able to log in to the new server as an existing user that already existed in the backup. I have never needed to do the 'first time log in' stuff as the default admin user. However now when the server is done setting up and I navigate to the log in page (we put it in Route 53 for DNS resolution) I get the Service Unavailable page. Maybe we now need to do the 'first time log in' stuff before moving the backup into place on the new server?

**Comment by jotamartos** [comment]
>Maybe we now need to do the 'first time log in' stuff before moving the backup into place on the new server? I did another deployment today using the same process and see that jenkins and apache are running

If everything works in that new deployment, and you can access the application, then there is something wrong in the previous deployment. I asked you to run the run.sh script to see if the java command returns any error when you run it. However, if you launched a new instance and it contains all your data, can't you simply start using that one and delete the failing one?

**Comment by mm808** [comment]
I cannot use the new deployment because when I go to the login page I get the Service Unavailable page. So while I see all the backup stuff in the jenkins home folder when I ssh onto the machine, the server is still useless since no one can log in to it from the Jenkins UI. 

_http://nameofserver.dev.company.com/_ results in page "It works!" (an apache message?)
_http://nameofserver.dev.company.com/login?from=%2F_ results in "Service Unavailable The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later." (a jenkins message?)

```
bitnami@ip-10-192-8-:~$ sudo /opt/bitnami/scripts/jenkins/run.sh
jenkins 18:57:07.58 INFO  ==> ** Starting Jenkins **
Running from: /opt/bitnami/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
2022-07-11 18:57:08.158+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @564ms to org.eclipse.jetty.util.log.JavaUtilLog
2022-07-11 18:57:08.250+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2022-07-11 18:57:08.281+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2022-07-11 18:57:08.346+0000 [id=1]	INFO	winstone.Logger#logInternal: Jetty shutdown successfully
java.io.IOException: Failed to start a listener: winstone.HttpsConnectorFactory
	at winstone.Launcher.spawnListener(Launcher.java:261)
	at winstone.Launcher.<init>(Launcher.java:190)
	at winstone.Launcher.main(Launcher.java:405)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Main._main(Main.java:342)
	at Main.main(Main.java:117)
Caused by: winstone.WinstoneException: No SSL key store found at /bitnami/jenkins/home/jenkins.jks
	at winstone.AbstractSecuredConnectorFactory.configureSsl(AbstractSecuredConnectorFactory.java:66)
	at winstone.HttpsConnectorFactory.start(HttpsConnectorFactory.java:54)
	at winstone.Launcher.spawnListener(Launcher.java:255)
	... 8 more
2022-07-11 18:57:08.347+0000 [id=1]	SEVERE	winstone.Logger#logInternal: Container startup failed
winstone.WinstoneException: No SSL key store found at /bitnami/jenkins/home/jenkins.jks
	at winstone.AbstractSecuredConnectorFactory.configureSsl(AbstractSecuredConnectorFactory.java:66)
	at winstone.HttpsConnectorFactory.start(HttpsConnectorFactory.java:54)
	at winstone.Launcher.spawnListener(Launcher.java:255)
Caused: java.io.IOException: Failed to start a listener: winstone.HttpsConnectorFactory
	at winstone.Launcher.spawnListener(Launcher.java:261)
	at winstone.Launcher.<init>(Launcher.java:190)
	at winstone.Launcher.main(Launcher.java:405)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Main._main(Main.java:342)
	at Main.main(Main.java:117)
```

**Comment by jotamartos** [comment]
> Caused by: winstone.WinstoneException: No SSL key store found at /bitnami/jenkins/home/jenkins.jks
> 	at winstone.AbstractSecuredConnectorFactory.configureSsl(AbstractSecuredConnectorFactory.java:66)
> 	at winstone.HttpsConnectorFactory.start(HttpsConnectorFactory.java:54)
> 	at winstone.Launcher.spawnListener(Launcher.java:255)
> 	... 8 more

The error is clear, it seems there is not an SSL key in that path. I do not know if you removed/renamed it but Jenkins is looking for the key there. Please take a look at the [Jenkins' documentation and forums](https://www.jenkins.io/participate/connect/) to know what to do to fix that error. Once you generate the key, Jenkins should run properly.
